shutdown_costmaps: false
controller_frequency: 10.0
planner_patience: 5.0
controller_patience: 15.0
conservative_reset_dist: 3.0
planner_frequency: 5.0
oscillation_timeout: 10.0
oscillation_distance: 0.2

base_global_planner: navfn/NavfnROS
base_local_planner: dwa_local_planner/DWAPlannerROS

DWAPlannerROS:
  max_vel_trans: 4.0
  min_vel_trans: 0.1
  max_vel_x: 0.1
  min_vel_x: -0.1
  max_vel_theta: 2.0
  min_vel_theta: 1.0
  acc_lim_x: 1.0
  acc_lim_y: 0.0
  acc_lim_theta: 10.0
  acc_lim_trans: 3.0
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.2
  sim_time: 1.0
